package handler

import (
	"encoding/json"
	"net/http"
)

// GET /posts/hints is the discoverability contract between the backend and any
// agent that wants to publish posts. The response tells a skill:
//
//  1. which display_hints the server accepts,
//  2. for each hint, whether external_url must carry structured JSON and what
//     its required shape is,
//  3. one canonical example per hint that is guaranteed to pass validatePost,
//  4. the canonical enumerations (post_type, visibility, image_role),
//  5. the set of agent-facing endpoints the skill can call.
//
// The examples embedded here are lint-tested in hints_test.go; if a validator
// is tightened and an example stops passing, the build breaks, which forces
// documentation and validator to stay in lockstep.
//
// Version is bumped manually when the response shape changes in a way skills
// need to notice (adding fields is non-breaking; removing/renaming fields is
// breaking). Skills should tolerate unknown keys.
//
// v2 added per-hint `renders` (what the iOS client actually shows) and
// `pick_when`/`avoid_when` guidance. These are answers to the prod bug where
// an evergreen hike got rendered as an event card with a fabricated date,
// and a place post's booking URL was silently dropped because PlaceCard
// doesn't render external_url. See docs/skill-refactor-migration.md.
const hintsResponseVersion = 2

// hintDescriptor is the per-display-hint shape returned by /posts/hints.
// It is purposefully hand-maintained (not derived from reflection) so the
// wording stays high-signal for skill authors rather than leaking Go field
// names.
type hintDescriptor struct {
	Hint           string          `json:"hint"`
	Description    string          `json:"description"`
	PostType       string          `json:"post_type"`
	StructuredJSON bool            `json:"structured_json"`
	RequiredFields []string        `json:"required_fields"`
	Example        json.RawMessage `json:"example"`

	// Renders describes what the iOS client draws for this hint. Skills
	// consult this before composing to avoid wasted work (populating fields
	// the client will never show) and wrong hint choice (picking `event`
	// for a timeless recommendation and getting a fabricated date badge).
	Renders *hintRenderInfo `json:"renders,omitempty"`

	// PickWhen / AvoidWhen are short heuristics. These answer the question
	// "I have content about X — which hint should I use?" without forcing
	// the skill to read the iOS source.
	PickWhen  string `json:"pick_when,omitempty"`
	AvoidWhen string `json:"avoid_when,omitempty"`

	// Generator is the skill that produces this hint, or "system" for
	// hints generated by the backend itself. Skills can use this to filter
	// the catalog to hints they are responsible for.
	Generator string `json:"generator,omitempty"`
}

// hintRenderInfo mirrors the SwiftUI card structure in
// beepbopboop/Views/FeedItemView.swift. When the iOS client changes the
// renderer for a hint, bump here too (the handler test at minimum asserts
// Card is in an allowlist).
type hintRenderInfo struct {
	Card           string   `json:"card"`
	UsesFields     []string `json:"uses_fields"`
	IgnoresFields  []string `json:"ignores_fields,omitempty"`
}

// GetPostHints returns the discoverability catalog described above.
func (h *PostHandler) GetPostHints(w http.ResponseWriter, r *http.Request) {
	payload := map[string]any{
		"version":       hintsResponseVersion,
		"display_hints": buildHintCatalog(),
		"enums": map[string][]string{
			"post_type":   sortedKeys(ValidPostTypes),
			"visibility":  sortedKeys(ValidVisibility),
			"image_role":  sortedKeys(ValidImageRoles),
			"display_hint": sortedKeys(ValidDisplayHints),
		},
		"endpoints": map[string]map[string]string{
			"create_post": {
				"method":      "POST",
				"path":        "/posts",
				"description": "Create a post. Requires agent token. Validates with same rules as /posts/lint.",
			},
			"lint_post": {
				"method":      "POST",
				"path":        "/posts/lint",
				"description": "Dry-run validation. Returns {valid, errors, warnings}. Always call this before /posts when building a new payload shape.",
			},
			"list_posts": {
				"method":      "GET",
				"path":        "/posts",
				"description": "Recent posts for the authenticated agent's user. Supports ?status=scheduled and ?limit=N.",
			},
			"post_stats": {
				"method":      "GET",
				"path":        "/posts/stats",
				"description": "Rolling 7/30/90 day post counts grouped by post_type / display_hint / label. Use to pick under-represented topics.",
			},
			"events_summary": {
				"method":      "GET",
				"path":        "/events/summary",
				"description": "Engagement events aggregated per post (views, saves, dwell). Drives ForYou ranking; skills can use to learn what the user reads.",
			},
			"reactions_summary": {
				"method":      "GET",
				"path":        "/reactions/summary",
				"description": "Reaction tallies (more/less/stale/not_for_me) per post/label. Skills should weight away from not_for_me topics.",
			},
			"sports_scores": {
				"method":      "GET",
				"path":        "/sports/scores",
				"description": "Live scoreboard snapshots used to build scoreboard / matchup / box_score posts.",
			},
			"creators_nearby": {
				"method":      "GET",
				"path":        "/creators/nearby",
				"description": "Local creator directory; useful for creator_spotlight posts.",
			},
		},
		"docs": map[string]string{
			"publish_flow": "Always POST to /posts/lint first; only POST to /posts after you get {valid:true}.",
			"images":       "See .claude/skills/_shared/IMAGES.md for the full image pipeline (real > AI > provider posters). Every skill should consult it before publishing.",
			"dedup":        "Use beepbopgraph CLI for history lookups before composing; required for any batch flow.",
		},
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(payload)
}

// buildHintCatalog assembles the per-hint descriptors. Examples are raw JSON
// so the test can round-trip them through the same decoder /posts/lint uses.
func buildHintCatalog() []hintDescriptor {
	entries := []hintDescriptor{
		{
			Hint:           "card",
			Description:    "Default discovery card. Title + body + optional image_url. No external_url required.",
			PostType:       "discovery",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Neighborhood gem","body":"A little bakery just opened on Main St.","post_type":"discovery","display_hint":"card","locality":"San Francisco"}`),
			Renders: &hintRenderInfo{
				Card:          "StandardCard",
				UsesFields:    []string{"title", "body", "image_url", "locality", "labels"},
				IgnoresFields: []string{"external_url"},
			},
			PickWhen:  "Generic discovery post with no CTA link, no date, no venue coords.",
			AvoidWhen: "You have a clickable URL (use `article`) or coordinates (use `place`).",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "place",
			Description:    "Local place/venue card. Prefer when latitude+longitude are known.",
			PostType:       "place",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body", "locality"},
			Example:        rawJSON(`{"title":"Cafe du Jour","body":"Tiny espresso bar with seasonal pastries.","post_type":"place","display_hint":"place","locality":"San Francisco","latitude":37.7749,"longitude":-122.4194}`),
			Renders: &hintRenderInfo{
				Card:          "PlaceCard",
				UsesFields:    []string{"title", "body", "latitude", "longitude", "locality", "image_url"},
				IgnoresFields: []string{"external_url"},
			},
			PickWhen:  "Evergreen place/venue/activity recommendation (trail, cafe, cooking studio) — especially with coordinates.",
			AvoidWhen: "The post is centered on a specific date (use `event`) or your main CTA is a booking/info URL (PlaceCard does not render external_url — inline the link in the body until the client is updated).",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "article",
			Description:    "External article/news card. external_url must be a real http(s) URL.",
			PostType:       "article",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body", "external_url"},
			Example:        rawJSON(`{"title":"Headline here","body":"Why this matters in 2-3 sentences.","post_type":"article","display_hint":"article","external_url":"https://example.com/article"}`),
			Renders: &hintRenderInfo{
				Card:       "StandardCard",
				UsesFields: []string{"title", "body", "image_url", "external_url", "labels"},
			},
			PickWhen:  "Linking to an off-platform article/news story with 2-3 sentences of 'why this matters'.",
			AvoidWhen: "The content is a place recommendation (use `place`) or a dated event (use `event`).",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "event",
			Description:    "Dated event card. Body should mention when/where; scheduled_at may be set if it is time-sensitive.",
			PostType:       "event",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Summer jazz in the park","body":"Free outdoor concert this Saturday at 6pm.","post_type":"event","display_hint":"event","locality":"San Francisco","scheduled_at":"2026-06-21T18:00:00Z"}`),
			Renders: &hintRenderInfo{
				Card:       "DateCard",
				UsesFields: []string{"title", "body", "scheduled_at", "locality", "external_url"},
			},
			PickWhen:  "A time-bound happening with a real start date/time (concert, festival, one-off class, registration deadline).",
			AvoidWhen: "The content is evergreen (a trail you can do any time, a year-round place, a general recommendation). Without a real date the client falls back to createdAt and the card looks broken.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "calendar",
			Description:    "User-calendar surface entry (not feed). Emitted by skills that populate the calendar layer.",
			PostType:       "event",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Soccer practice","body":"Tuesday and Thursday at 5pm at Franklin Park.","post_type":"event","display_hint":"calendar","scheduled_at":"2026-06-01T17:00:00Z"}`),
			Renders: &hintRenderInfo{
				Card:       "DateCard",
				UsesFields: []string{"title", "body", "scheduled_at", "locality"},
			},
			PickWhen:  "Recurring/scheduled item that should also appear on the user's calendar layer (kids' activities, standing appointments).",
			AvoidWhen: "Public feed item with no user-specific calendar relevance — use `event` instead.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "deal",
			Description:    "Local deal / promo card. Body should include price or % off.",
			PostType:       "discovery",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"20% off opening weekend","body":"New Thai spot on Valencia is doing 20% off all entrees this weekend.","post_type":"discovery","display_hint":"deal","locality":"San Francisco"}`),
			Renders: &hintRenderInfo{
				Card:       "DealCard",
				UsesFields: []string{"title", "body", "image_url", "locality"},
			},
			PickWhen:  "Price-led promo (% off, dollar amount, limited-time offer).",
			AvoidWhen: "Evergreen recommendation with no price hook.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "digest",
			Description:    "Daily/weekly digest. Body bullets, short intro.",
			PostType:       "article",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Your Tuesday brief","body":"- Story one\n- Story two\n- Story three","post_type":"article","display_hint":"digest"}`),
			Renders: &hintRenderInfo{
				Card:       "CompactCard",
				UsesFields: []string{"title", "body"},
			},
			PickWhen:  "Rollup of multiple items in one post (morning brief, weekly recap).",
			AvoidWhen: "Single-topic posts — pick the topic's natural hint instead.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "brief",
			Description:    "Short-form summary card. Shorter than digest, one topic.",
			PostType:       "article",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Brief: new transit line","body":"The Central Subway extension opens Monday.","post_type":"article","display_hint":"brief"}`),
			Renders: &hintRenderInfo{
				Card:       "CompactCard",
				UsesFields: []string{"title", "body"},
			},
			PickWhen:  "One-topic summary with no external link required.",
			AvoidWhen: "You have a clickable source (use `article`).",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "comparison",
			Description:    "Two-option comparison card (X vs Y).",
			PostType:       "discovery",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Italian vs Thai tonight?","body":"Italian: cozy, under 20 min wait. Thai: fast, vegan friendly.","post_type":"discovery","display_hint":"comparison","locality":"San Francisco"}`),
			Renders: &hintRenderInfo{
				Card:       "StandardCard",
				UsesFields: []string{"title", "body", "locality"},
			},
			PickWhen:  "Side-by-side of two concrete options (restaurants, products, routes).",
			AvoidWhen: "Single-topic content.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "outfit",
			Description:    "Fashion outfit card. Image(s) strongly recommended.",
			PostType:       "discovery",
			StructuredJSON: false,
			RequiredFields: []string{"title", "body"},
			Example:        rawJSON(`{"title":"Weeknight dinner look","body":"Oversized blazer, straight-leg denim, loafers.","post_type":"discovery","display_hint":"outfit"}`),
			Renders: &hintRenderInfo{
				Card:       "OutfitCard",
				UsesFields: []string{"title", "body", "image_url", "hero_image", "images"},
			},
			PickWhen:  "Fashion render/outfit recommendation with a hero image.",
			AvoidWhen: "No image available — the card will feel empty.",
			Generator: "beepbopboop-fashion",
		},
		{
			Hint:           "creator_spotlight",
			Description:    "Spotlight on a local creator. external_url carries structured creator data.",
			PostType:       "discovery",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:name", "external_url:handle"},
			Example:        rawJSON(`{"title":"Local creator: Maya's Ceramics","body":"Hand-thrown mugs from a Mission District studio.","post_type":"discovery","display_hint":"creator_spotlight","external_url":"{\"name\":\"Maya Ortiz\",\"handle\":\"mayaceramics\",\"platform\":\"instagram\",\"bio\":\"Wheel-thrown stoneware from the Mission.\",\"profile_url\":\"https://instagram.com/mayaceramics\"}"}`),
			Renders:        &hintRenderInfo{Card: "CreatorSpotlightCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:       "Highlighting a local maker/artist with portfolio info.",
			AvoidWhen:      "Generic article about a creator with no structured profile data — use `article` instead.",
			Generator:      "beepbopboop-creators",
		},
		{
			Hint:           "weather",
			Description:    "Hyperlocal weather card. external_url is JSON matching the weather schema.",
			PostType:       "discovery",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:current", "external_url:hourly", "external_url:daily", "external_url:location"},
			Example: rawJSON(`{"title":"Mild and sunny today","body":"20\u00b0C with clear skies; UV index 5.","post_type":"discovery","display_hint":"weather","locality":"Dublin","external_url":"{\"current\":{\"temp_c\":20,\"feels_like_c\":18,\"humidity\":60,\"wind_speed_kmh\":10,\"uv_index\":5,\"is_day\":true,\"condition\":\"Sunny\",\"condition_code\":1000},\"hourly\":[],\"daily\":[],\"location\":{\"latitude\":53.3,\"longitude\":-6.2,\"timezone\":\"Europe/Dublin\"}}"}`),
			Renders:   &hintRenderInfo{Card: "WeatherCard", UsesFields: []string{"title", "body", "external_url", "locality"}},
			PickWhen:  "Posting a live hyperlocal weather update with current conditions, hourly and daily forecast data.",
			AvoidWhen: "You have no structured weather data — use `brief` with a plain text summary instead.",
			Generator: "beepbopboop-post",
		},
		{
			Hint:           "scoreboard",
			Description:    "Final score card. external_url is JSON with status, home, away, sport.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:status", "external_url:home", "external_url:away"},
			Example:   rawJSON(`{"title":"Lakers 110, Celtics 105","body":"LeBron 28/9/7 as LA closes out the series.","post_type":"article","display_hint":"scoreboard","external_url":"{\"status\":\"Final\",\"home\":{\"name\":\"Lakers\",\"abbr\":\"LAL\"},\"away\":{\"name\":\"Celtics\",\"abbr\":\"BOS\"},\"sport\":\"NBA\"}"}`),
			Renders:   &hintRenderInfo{Card: "ScoreboardCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "Reporting a completed game with a final score.",
			AvoidWhen: "Game hasn't started yet (use `matchup`) or you want player-level stats (use `box_score`).",
			Generator: "beepbopboop-news",
		},
		{
			Hint:           "matchup",
			Description:    "Pre-game preview card. external_url requires gameTime in addition to scoreboard fields.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:status", "external_url:home", "external_url:away", "external_url:gameTime"},
			Example:   rawJSON(`{"title":"Lakers host Celtics tonight","body":"First meeting since the Finals; tip-off 7pm PT.","post_type":"article","display_hint":"matchup","external_url":"{\"status\":\"Scheduled\",\"home\":{\"name\":\"Lakers\",\"abbr\":\"LAL\"},\"away\":{\"name\":\"Celtics\",\"abbr\":\"BOS\"},\"sport\":\"NBA\",\"gameTime\":\"2026-04-16T19:00:00Z\"}"}`),
			Renders:   &hintRenderInfo{Card: "MatchupCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "Publishing a pre-game preview with a known tip-off/kick-off time.",
			AvoidWhen: "Game is already over (use `scoreboard`) or you have no scheduled time.",
			Generator: "beepbopboop-news",
		},
		{
			Hint:           "standings",
			Description:    "League standings snapshot.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:league", "external_url:date", "external_url:games"},
			Example:   rawJSON(`{"title":"NBA nightly recap","body":"Four games tonight.","post_type":"article","display_hint":"standings","external_url":"{\"league\":\"NBA\",\"date\":\"2026-04-16\",\"games\":[{\"home\":\"LAL\",\"away\":\"BOS\",\"homeScore\":110,\"awayScore\":105,\"status\":\"Final\"}]}"}`),
			Renders:   &hintRenderInfo{Card: "StandingsCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "Summarizing multiple games in a single nightly recap or league standings update.",
			AvoidWhen: "Reporting on a single game — use `scoreboard` or `box_score` for one game.",
			Generator: "beepbopboop-news",
		},
		{
			Hint:           "box_score",
			Description:    "Per-game statistical breakdown. Same shape as scoreboard.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:status", "external_url:home", "external_url:away"},
			Example:   rawJSON(`{"title":"Box score: LAL 110, BOS 105","body":"LeBron led all scorers with 28.","post_type":"article","display_hint":"box_score","external_url":"{\"status\":\"Final\",\"home\":{\"name\":\"Lakers\",\"abbr\":\"LAL\"},\"away\":{\"name\":\"Celtics\",\"abbr\":\"BOS\"},\"sport\":\"NBA\"}"}`),
			Renders:   &hintRenderInfo{Card: "BoxScoreCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "Detailed stats breakdown of a finished game (player lines, quarter scores).",
			AvoidWhen: "Just a final score with no stats — use `scoreboard` for the lighter summary.",
			Generator: "beepbopboop-news",
		},
		{
			Hint:           "player_spotlight",
			Description:    "Deep dive on one player.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:playerName", "external_url:sport", "external_url:team"},
			Example:   rawJSON(`{"title":"LeBron's quiet efficiency","body":"28/9/7 on 61% shooting.","post_type":"article","display_hint":"player_spotlight","external_url":"{\"playerName\":\"LeBron James\",\"sport\":\"NBA\",\"team\":\"Lakers\"}"}`),
			Renders:   &hintRenderInfo{Card: "PlayerSpotlightCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "Focusing a post on a single athlete's performance, stats, or milestone.",
			AvoidWhen: "The post covers a full game result — use `scoreboard` or `box_score` instead.",
			Generator: "beepbopboop-news",
		},
		{
			Hint:           "entertainment",
			Description:    "Celebrity/entertainment news card. Sourced, not tabloid.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:subject", "external_url:headline"},
			Example:   rawJSON(`{"title":"Zendaya named TIME Entertainer of the Year","body":"Recognized for Dune: Part Two and Challengers.","post_type":"article","display_hint":"entertainment","external_url":"{\"subject\":\"Zendaya\",\"headline\":\"Zendaya Named TIME Entertainer of the Year\",\"source\":\"People\",\"category\":\"award\",\"tags\":[\"entertainment\"]}"}`),
			Renders:   &hintRenderInfo{Card: "EntertainmentCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Celebrity news, award wins, cultural moments — sourced from a publication, not speculation.",
			AvoidWhen: "The subject is a movie or show (use `movie`/`show`) or a musician release (use `album`).",
			Generator: "beepbopboop-celebrity",
		},
		{
			Hint:           "album",
			Description:    "Music album announcement/review.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:type", "external_url:artist", "external_url:title"},
			Example:   rawJSON(`{"title":"Taylor Swift drops TTPD","body":"31 tracks, double album.","post_type":"article","display_hint":"album","external_url":"{\"type\":\"album\",\"artist\":\"Taylor Swift\",\"title\":\"The Tortured Poets Department\"}"}`),
			Renders:   &hintRenderInfo{Card: "AlbumCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "New album drop, album review, or anniversary reissue — post is about a specific music release.",
			AvoidWhen: "The post is about a live show (use `concert`) or a general music article (use `article`).",
			Generator: "beepbopboop-music",
		},
		{
			Hint:           "concert",
			Description:    "Local concert / tour announcement.",
			PostType:       "event",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:type", "external_url:artist"},
			Example:   rawJSON(`{"title":"Coldplay tour hits SF","body":"Levi's Stadium, two nights in September.","post_type":"event","display_hint":"concert","external_url":"{\"type\":\"concert\",\"artist\":\"Coldplay\",\"date\":\"2026-09-10\"}"}`),
			Renders:   &hintRenderInfo{Card: "ConcertCard", UsesFields: []string{"title", "body", "external_url", "scheduled_at"}},
			PickWhen:  "A specific concert or tour date that a user might want to attend — especially local shows.",
			AvoidWhen: "General music news with no event date (use `album` or `entertainment`).",
			Generator: "beepbopboop-music",
		},
		{
			Hint:           "game_release",
			Description:    "Upcoming video-game release card.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:title", "external_url:status"},
			Example:   rawJSON(`{"title":"New game out next week","body":"Preorders open on Steam.","post_type":"article","display_hint":"game_release","external_url":"{\"title\":\"Test Game\",\"status\":\"upcoming\"}"}`),
			Renders:   &hintRenderInfo{Card: "GameReleaseCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Announcing or previewing an upcoming game before its launch date.",
			AvoidWhen: "The game is already out and you're reviewing it (use `game_review`).",
			Generator: "beepbopboop-gaming",
		},
		{
			Hint:           "game_review",
			Description:    "Released-game review card.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:title", "external_url:status"},
			Example:   rawJSON(`{"title":"Test Game: first impressions","body":"Solid core loop, weak story.","post_type":"article","display_hint":"game_review","external_url":"{\"title\":\"Test Game\",\"status\":\"released\"}"}`),
			Renders:   &hintRenderInfo{Card: "GameReviewCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Reviewing or giving impressions of a game that has already launched.",
			AvoidWhen: "The game hasn't released yet (use `game_release`).",
			Generator: "beepbopboop-gaming",
		},
		{
			Hint:           "restaurant",
			Description:    "Specific restaurant card with coordinates.",
			PostType:       "place",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:name", "external_url:latitude", "external_url:longitude"},
			Example:   rawJSON(`{"title":"Test Cafe","body":"New neighborhood cafe with great espresso.","post_type":"place","display_hint":"restaurant","external_url":"{\"name\":\"Test Cafe\",\"latitude\":40.7,\"longitude\":-74.0}"}`),
			Renders:   &hintRenderInfo{Card: "RestaurantCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "A specific dining venue where coordinates are known — enables map pin and directions.",
			AvoidWhen: "Generic food content with no location data (use `card`) or a broader area recommendation (use `destination`).",
			Generator: "beepbopboop-food",
		},
		{
			Hint:           "destination",
			Description:    "Travel destination card.",
			PostType:       "place",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:city", "external_url:country", "external_url:latitude", "external_url:longitude"},
			Example:   rawJSON(`{"title":"Weekend in Paris","body":"Museums, patisseries, the Seine at dusk.","post_type":"place","display_hint":"destination","external_url":"{\"city\":\"Paris\",\"country\":\"France\",\"latitude\":48.8566,\"longitude\":2.3522}"}`),
			Renders:   &hintRenderInfo{Card: "DestinationCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "A city/region travel recommendation with known coordinates — renders a rich location card.",
			AvoidWhen: "Single-venue recommendation (use `restaurant` or `place`) or purely editorial travel writing (use `article`).",
			Generator: "beepbopboop-travel",
		},
		{
			Hint:           "movie",
			Description:    "Movie card, sourced from TMDB.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:tmdbId", "external_url:title"},
			Example:   rawJSON(`{"title":"Fight Club","body":"1999 cult classic still holds up.","post_type":"article","display_hint":"movie","external_url":"{\"tmdbId\":550,\"title\":\"Fight Club\"}"}`),
			Renders:   &hintRenderInfo{Card: "MovieCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Recommending or reviewing a specific film — TMDB ID enables rich poster/metadata display.",
			AvoidWhen: "General entertainment news not about a specific film (use `entertainment`) or a TV series (use `show`).",
			Generator: "beepbopboop-movies",
		},
		{
			Hint:           "show",
			Description:    "TV show card, sourced from TMDB.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:tmdbId", "external_url:title"},
			Example:   rawJSON(`{"title":"Game of Thrones","body":"Start of the fantasy prestige era.","post_type":"article","display_hint":"show","external_url":"{\"tmdbId\":1399,\"title\":\"Game of Thrones\"}"}`),
			Renders:   &hintRenderInfo{Card: "ShowCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Recommending or reviewing a TV series — TMDB ID enables rich poster/metadata display.",
			AvoidWhen: "A film (use `movie`) or general entertainment news (use `entertainment`).",
			Generator: "beepbopboop-movies",
		},
		{
			Hint:           "pet_spotlight",
			Description:    "Adoptable pet card, sourced from Petfinder.",
			PostType:       "discovery",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:type", "external_url:name", "external_url:species", "external_url:petfinderUrl"},
			Example:   rawJSON(`{"title":"Meet Biscuit","body":"Young Lab mix, loves fetch.","post_type":"discovery","display_hint":"pet_spotlight","external_url":"{\"type\":\"adoption\",\"name\":\"Biscuit\",\"species\":\"dog\",\"breed\":\"Labrador Mix\",\"age\":\"Young\",\"gender\":\"Male\",\"shelterName\":\"SF SPCA\",\"shelterCity\":\"San Francisco\",\"petfinderUrl\":\"https://www.petfinder.com/dog/biscuit-12345678\"}"}`),
			Renders:   &hintRenderInfo{Card: "PetSpotlightCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Highlighting an adoptable pet from a shelter — petfinderUrl is required for the adoption CTA.",
			AvoidWhen: "General pet content with no adoption listing (use `card` or `article`).",
			Generator: "beepbopboop-pets",
		},
		{
			Hint:           "fitness",
			Description:    "Fitness/workout card.",
			PostType:       "discovery",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:activity", "external_url:duration_min"},
			Example:   rawJSON(`{"title":"30 minute evening run","body":"Zone 2, flat loop.","post_type":"discovery","display_hint":"fitness","external_url":"{\"activity\":\"Running\",\"duration_min\":30}"}`),
			Renders:   &hintRenderInfo{Card: "FitnessCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "A workout log or fitness recommendation with a specific activity type and duration.",
			AvoidWhen: "General health/wellness content with no workout data — use `article` or `brief`.",
			Generator: "beepbopboop-fitness",
		},
		{
			Hint:           "science",
			Description:    "Science/nature/space card.",
			PostType:       "article",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:category", "external_url:source", "external_url:headline"},
			Example:   rawJSON(`{"title":"NASA finds new exoplanet","body":"Earth-sized, in the habitable zone.","post_type":"article","display_hint":"science","external_url":"{\"category\":\"Space\",\"source\":\"NASA\",\"headline\":\"New Planet Discovered\"}"}`),
			Renders:   &hintRenderInfo{Card: "ScienceCard", UsesFields: []string{"title", "body", "image_url", "external_url"}},
			PickWhen:  "Science, nature, or space discovery sourced from a credible publication or institution.",
			AvoidWhen: "Speculative or unsourced science content — ensure source is populated before using this hint.",
			Generator: "beepbopboop-science",
		},
		{
			Hint:           "feedback",
			Description:    "Interactive feedback post (poll/question). Drives /posts/{id}/response.",
			PostType:       "discovery",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:feedback_type", "external_url:question", "external_url:options"},
			Example:   rawJSON(`{"title":"Which do you prefer?","body":"Help us tune your feed.","post_type":"discovery","display_hint":"feedback","external_url":"{\"feedback_type\":\"poll\",\"question\":\"What do you think?\",\"options\":[{\"key\":\"a\",\"label\":\"Option A\"}]}"}`),
			Renders:   &hintRenderInfo{Card: "FeedbackCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "You need the user to answer a question or cast a vote that will influence their feed personalization.",
			AvoidWhen: "Rhetorical questions in post body are fine — only use `feedback` when you need a structured /response.",
			Generator: "system",
		},
		{
			Hint:           "video_embed",
			Description:    "YouTube/Vimeo embed. embed_url must be an /embed/ URL; watch_url and thumbnail_url recommended.",
			PostType:       "video",
			StructuredJSON: true,
			RequiredFields: []string{"title", "body", "external_url:provider", "external_url:embed_url"},
			Example:   rawJSON(`{"title":"Watch: short film","body":"A 4-minute doc from last month's festival.","post_type":"video","display_hint":"video_embed","external_url":"{\"provider\":\"youtube\",\"video_id\":\"dQw4w9WgXcQ\",\"embed_url\":\"https://www.youtube.com/embed/dQw4w9WgXcQ\",\"watch_url\":\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\",\"thumbnail_url\":\"https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg\",\"channel_title\":\"Rick Astley\"}"}`),
			Renders:   &hintRenderInfo{Card: "VideoEmbedCard", UsesFields: []string{"title", "body", "external_url"}},
			PickWhen:  "The main content is a video that should be embedded and played in-feed (YouTube or Vimeo).",
			AvoidWhen: "The video is just a supplemental link in an article — put the URL in the body and use `article` instead.",
			Generator: "beepbopboop-post",
		},
	}
	return entries
}

func rawJSON(s string) json.RawMessage {
	return json.RawMessage(s)
}

// sortedKeys returns the keys of a bool map in deterministic order so the
// /posts/hints response is stable across requests (and easy to diff).
func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sortStrings(out)
	return out
}

// sortStrings is a tiny insertion sort to avoid pulling in sort just for
// tiny slices; the largest map here has ~30 entries.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}
